### ISSUE TITLE
Compile images with opcache?

### ISSUE THREAD

**Issue by B-Galati** [phpdaily/php#5]
Hello!

Everything is in the tittle :-)

I am asking this question following this conversation -> https://twitter.com/ArkadiuszKondas/status/1118977968028770304

Cheers!

**Comment by jdecool** [comment]
Hi @B-Galati,

Sorry for the delay of my answer, but 2 month later, I've just saw this issue.

phpdaily provide a base image for PHP development branches. Those can be extended.

Like the official PHP docker image, there is some command line app to configure (`docker-php-ext-configure`), compile (`docker-php-ext-install`) and enable (`docker-php-ext-enable`) some PHP extensions.

If you want to enable `opcache`, you can write this `Dockerfile` :

```docker
FROM phpdaily/php:8.0-dev

RUN docker-php-ext-install opcache
```

**Comment by B-Galati** [comment]
Thanks it makes sense but it would be more convenient to have it pre-installed in the image or having a special tag with opcache installed.
