### ISSUE TITLE
Install composer

### ISSUE THREAD

**Issue by martinssipenko** [phpdaily/php#6]
Would be great to have composer installed in images, so they can be used in CI.

**Comment by jdecool** [comment]
Hello @martinssipenko,

Thanks for your interest for this project.

phpdaily was created to provide a base image to work with PHP development branches and future releases at early stage.

So we don't want to include extra tools in the default image.

Base images can easily be extended to install PHP extensions or common tools. In this way, you can create your own docker image with what you want like Composer or install the tool directly from your CI job.

An example :

```docker
FROM phpdaily/php:8.0-dev

RUN curl --show-error --silent https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod a+x /usr/local/bin/composer
```
